modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="memory_of_the_past"
version="1.6.1"
displayName="Memories of the past"
displayURL="https://meherbensalem.github.io"
logoFile="logo.png"
credits="Thank you @porogulaemeo"
authors="NAIZO"
description="As players explore the world, they collect Memories from significant defeating a bosses or mobs. you can use this fragments to level up and gain extra stats."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.memory_of_the_past]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.65,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.memory_of_the_past]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration