
["Attribute 1"]
	tip_to_display = "§7Represents your overall durability. §7More health means you can survive longer in battle"
	#Make sure the command contain '(variable)' so you can update the attribute
	cmd_to_exc = ["/attribute @p generic.max_health base set (variable)"]
	display_name = "Vitality"

["Attribute 2"]
	tip_to_display = "§7Defines the amount of harm you can inflict with each attack. "
	#Make sure the command contain '(variable)' so you can update the attribute
	cmd_to_exc = ["/attribute @p generic.attack_damage base set (variable)"]
	display_name = "Attack Power"

["Attribute 3"]
	tip_to_display = "§7Determines how quickly you can swing your weapon. "
	#Make sure the command contain '(variable)' so you can update the attribute
	cmd_to_exc = ["/attribute @p generic.attack_speed base set (variable)"]
	display_name = "Attack Speed"

["Attribute 4"]
	tip_to_display = "§7Reduces the amount of damage you take from enemy attacks"
	#Make sure the command contain '(variable)' so you can update the attribute
	cmd_to_exc = ["/attribute @p generic.armor base set (variable)"]
	display_name = "Protection"

["Attribute 5"]
	tip_to_display = "§7Influences how fast you can move"
	#Make sure the command contain '(variable)' so you can update the attribute
	cmd_to_exc = ["/attribute @p generic.movement_speed base set (variable)"]
	display_name = "Agility"

["Attribute 6"]
	tip_to_display = "§7Reduces the distance you are pushed back when hit by an enemy or explosion"
	#Make sure the command contain '(variable)' so you can update the attribute
	cmd_to_exc = ["/attribute @p generic.knockback_resistance base set (variable) "]
	display_name = "Fortitude"

["Attribute 7"]
	tip_to_display = "§7Influences the chances of receiving better loot or triggering beneficial events"
	#Make sure the command contain '(variable)' so you can update the attribute
	cmd_to_exc = ["/attribute @p generic.luck base set (variable)"]
	display_name = "Exploration"

