
["Attribute 1"]
	max_level = 100.0
	tip_to_display = "§7Represents your overall durability. §7More health means you can survive longer in battle"
	lock = false
	cmd_to_exc = ["/attribute @p generic.max_health base set", "/effect give @p minecraft:instant_health 2 3"]
	base_value_per_point = 1.0
	display_name = "Vitality : "

["Attribute 2"]
	max_level = 100.0
	tip_to_display = "§7Defines the amount of harm you can inflict with each attack. "
	lock = false
	cmd_to_exc = ["/attribute @p generic.attack_damage base set"]
	base_value_per_point = 1.0
	display_name = "Attack Power : "

["Attribute 3"]
	max_level = 20.0
	tip_to_display = "§7Determines how quickly you can swing your weapon. "
	lock = false
	cmd_to_exc = ["/attribute @p generic.attack_speed base set"]
	base_value_per_point = 1.0
	display_name = "Attack Speed : "

["Attribute 4"]
	max_level = 200.0
	tip_to_display = "§7Reduces the amount of damage you take from enemy attacks"
	lock = false
	cmd_to_exc = ["/attribute @p generic.armor base set [param(0.1)]"]
	base_value_per_point = 1.0
	display_name = "Protection : "

["Attribute 5"]
	max_level = 50.0
	tip_to_display = "§7Influences how fast you can move"
	lock = false
	cmd_to_exc = ["/attribute @p generic.movement_speed base set [param(0.005)]"]
	base_value_per_point = 1.0
	display_name = "Agility : "

["Attribute 6"]
	max_level = 100.0
	tip_to_display = "§7Reduces the distance you are pushed back when hit by an enemy or explosion"
	lock = false
	cmd_to_exc = ["/attribute @p generic.knockback_resistance base set [param(0.01)]"]
	base_value_per_point = 1.0
	display_name = "Fortitude : "

["Attribute 7"]
	max_level = 100.0
	tip_to_display = "§7Influences the chances of receiving better loot or triggering beneficial events"
	lock = false
	cmd_to_exc = ["/attribute @p generic.luck base set [param(0.5)]"]
	base_value_per_point = 1.0
	display_name = "Exploration : "

["Attribute 8"]
	max_level = 0.0
	tip_to_display = ""
	lock = true
	cmd_to_exc = []
	base_value_per_point = 0.0
	display_name = ""

["Attribute 9"]
	"tip_to_display " = ""
	max_level = 0.0
	lock = true
	cmd_to_exc = []
	base_value_per_point = 0.0
	"display_name " = ""

["Attribute 10"]
	"tip_to_display " = ""
	max_level = 0.0
	lock = true
	cmd_to_exc = []
	base_value_per_point = 0.0
	"display_name " = ""

