
["HUD Overlay"]
	display_points_overlay = true
	display_level_overlay = true
	display_xp_overlay = true

["Leveling Config"]
	better_experience_value = 200.0
	level_per_orb = 1.0
	points_per_level = 1.0
	onDeathReset = false
	greater_experience_value = 2000.0
	enableDrops = true
	maxPlayerLevel = 500.0
	lesser_experience_value = 20.0
	scale_factor = 30.0

["Artifacts Settings"]
	bonus_experience_factor = 1.4

["Initial Starting Values"]
	init_val_attribute_eight = 0.0
	init_val_attribute_forth = 0.0
	init_val_attribute_sixth = 0.0
	init_val_attribute_nine = 0.0
	init_val_attribute_one = 20.0
	init_val_attribute_fifth = 20.0
	init_val_attribute_ten = 0.0
	init_val_attribute_two = 2.0
	init_val_attribute_three = 4.0
	init_val_attribute_seventh = 0.0
	init_val_starting_level = 1.0

["Leveling Scale"]
	level_interval_first = 20000.0
	level_interval_scale_first = 1.1
	level_interval_scale_second = 1.02
	starting_xp_level = 90.0
	level_interval_second = 100000.0
	level_interval_scale_after = 1.001

[Colors]
	global_stats_ui_color = "ยง6"

